// ⚠ AUTO-GENERATED by `dbcube generate` — do not edit by hand.
// Source of truth: your .table.cube files. Re-run after schema changes.

/** Table `customers` · database `ft_sqlite` */
export interface Customer {
    id: number;
    first_name: string;
    last_name: string;
    email: string | null;
    /** computed field (read-only, requires useComputes()) */
    full_name: string | null;
}

/** Shape accepted by insert()/update() for `customers` */
export interface NewCustomer {
    id?: number;
    first_name: string;
    last_name: string;
    email?: string | null;
}

/** Table `orders` · database `demo` */
export interface Order {
    id: number;
    user_id: number;
    product: string;
    total: number | null;
}

/** Shape accepted by insert()/update() for `orders` */
export interface NewOrder {
    id?: number;
    user_id: number;
    product: string;
    total?: number | null;
}

/** Table `users` · database `demo` */
export interface User {
    id: number;
    name: string;
    email: string | null;
    age: number | null;
    status: string | null;
    balance: number | null;
    /** computed field (read-only, requires useComputes()) */
    display_name: string | null;
}

/** Shape accepted by insert()/update() for `users` */
export interface NewUser {
    id?: number;
    name: string;
    email?: string | null;
    age?: number | null;
    status?: string | null;
    balance?: number | null;
}

/** Map of table name → row type. */
export interface DbSchema {
    customers: Customer;
    orders: Order;
    users: User;
}
